# Generated by Django 5.2 on 2025-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
