# Generated by Django 5.2 on 2025-04-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
    ]
